AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vget-APIのデータを更新するバッチ群
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs14.x

Resources:
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: vgetDataTable
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "dataType"
          KeyType: "RANGE"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "dataType"
          AttributeType: "S"
        - AttributeName: "dataValue"
          AttributeType: "S"
        - AttributeName: "publishedUnixTime"
          AttributeType: "N"
      GlobalSecondaryIndexes:
        - IndexName: "DataValueIndex"
          KeySchema:
            - AttributeName: "dataValue"
              KeyType: "HASH"
            - AttributeName: "publishedUnixTime"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "id"
  MakeVideoDataByChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/makeVideoDataByChannel
      Handler: index.lambdaHandler
      Environment:
        Variables:
          RUN_ENV: dev
      Policies:
        - S3ReadPolicy:
            BucketName: vget-api-channels
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable