AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vget-APIのデータを更新するバッチ群
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs14.x

Resources:
  MakeVideoDataByChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/makeVideoDataByChannel
      Handler: index.lambdaHandler
